### ISSUE TITLE
Sass filter fails with Django 1.5

### ISSUE THREAD

**Issue by gregplaysguitar** [miracle2k/webassets#244]
I'm getting some rather cryptic "OSError: [Errno 2] No such file or directory" errors trying to deploy a site. No indication is given as to *which* file or directory is missing, and files compile fine with `./manage.py assets build`. The error seems to require the following conditions:

- On-the-fly compilation of .scss files
- Apache/mod_wsgi (works fine with the runserver, and with uwsgi)
- Django 1.5.x (works fine with 1.4.2)

I'm using Ubuntu 10.04 and Python 2.6 - I haven't tested other versions of these - and Sass 3.2.9.

I suspected some sort of directory write permission coming through from apache, but haven't had any luck in that area. 

Details:

![screen shot 2013-05-30 at 2 53 46 pm](https://f.cloud.github.com/assets/23109/582995/2ebf789a-c8d4-11e2-8198-90eedc97cbb1.png)

Traceback (most recent call last):

  File "/home/greg/.virtualenvs/mikehewson/lib/python2.6/site-packages/django/core/handlers/base.py", line 153, in get_response
    response = callback(request, **param_dict)

  File "/home/greg/.virtualenvs/mikehewson/lib/python2.6/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)

  File "/home/greg/.virtualenvs/mikehewson/lib/python2.6/site-packages/django/views/defaults.py", line 26, in page_not_found
    return http.HttpResponseNotFound(template.render(RequestContext(request, {'request_path': request.path})))

  File "/home/greg/.virtualenvs/mikehewson/lib/python2.6/site-packages/django/template/base.py", line 140, in render
    return self._render(context)

  File "/home/greg/.virtualenvs/mikehewson/lib/python2.6/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)

  File "/home/greg/.virtualenvs/mikehewson/lib/python2.6/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)

  File "/home/greg/.virtualenvs/mikehewson/lib/python2.6/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)

  File "/home/greg/.virtualenvs/mikehewson/lib/python2.6/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)

  File "/home/greg/.virtualenvs/mikehewson/lib/python2.6/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)

  File "/home/greg/.virtualenvs/mikehewson/lib/python2.6/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)

  File "/home/greg/.virtualenvs/mikehewson/lib/python2.6/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)

  File "/home/greg/.virtualenvs/mikehewson/lib/python2.6/site-packages/django_assets/templatetags/assets.py", line 69, in render
    for url in bundle.urls(env=get_env()):

  File "/home/greg/.virtualenvs/mikehewson/lib/python2.6/site-packages/webassets/bundle.py", line 681, in urls
    urls.extend(bundle._urls(env, extra_filters, *args, **kwargs))

  File "/home/greg/.virtualenvs/mikehewson/lib/python2.6/site-packages/webassets/bundle.py", line 643, in _urls
    *args, **kwargs)

  File "/home/greg/.virtualenvs/mikehewson/lib/python2.6/site-packages/webassets/bundle.py", line 498, in _build
    force, disable_cache=disable_cache, extra_filters=extra_filters)

  File "/home/greg/.virtualenvs/mikehewson/lib/python2.6/site-packages/webassets/bundle.py", line 384, in _merge_and_apply
    filters_to_pass_down, disable_cache=disable_cache)

  File "/home/greg/.virtualenvs/mikehewson/lib/python2.6/site-packages/webassets/bundle.py", line 423, in _merge_and_apply
    kwargs=item_data)

  File "/home/greg/.virtualenvs/mikehewson/lib/python2.6/site-packages/webassets/merge.py", line 269, in apply
    return self._wrap_cache(key, func)

  File "/home/greg/.virtualenvs/mikehewson/lib/python2.6/site-packages/webassets/merge.py", line 216, in _wrap_cache
    content = func().getvalue()

  File "/home/greg/.virtualenvs/mikehewson/lib/python2.6/site-packages/webassets/merge.py", line 249, in func
    getattr(filter, type)(data, out, **kwargs_final)

  File "/home/greg/.virtualenvs/mikehewson/lib/python2.6/site-packages/webassets/filter/sass.py", line 151, in input
    self._apply_sass(_in, out, os.path.dirname(source_path))

  File "/home/greg/.virtualenvs/mikehewson/lib/python2.6/site-packages/webassets/filter/sass.py", line 132, in _apply_sass
    shell=(os.name == 'nt'))

  File "/usr/lib/python2.6/subprocess.py", line 633, in __init__
    errread, errwrite)

  File "/usr/lib/python2.6/subprocess.py", line 1139, in _execute_child
    raise child_exception

OSError: [Errno 2] No such file or directory

**Comment by miracle2k** [comment]
Closing for #400.
