### ISSUE TITLE
datauri doesn't work for me: "ValueError: Cannot determine url..."

### ISSUE THREAD

**Issue by dhardtke** [miracle2k/webassets#387]
I have the strange issue that I can't use datauri:
```
Traceback (most recent call last):
  File "process.py", line 66, in <module>
	print(bundle.urls())
  File "~/.local/lib/python3.3/site-packages/webassets/bundle.py", line 787, in urls
	urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
  File "~/.local/lib/python3.3/site-packages/webassets/bundle.py", line 746, in _urls
	*args, **kwargs)
  File "~/.local/lib/python3.3/site-packages/webassets/bundle.py", line 600, in _build
	force, disable_cache=disable_cache, extra_filters=extra_filters)
  File "~/.local/lib/python3.3/site-packages/webassets/bundle.py", line 485, in _merge_and_apply
	filters_to_pass_down, disable_cache=disable_cache)
  File "~/.local/lib/python3.3/site-packages/webassets/bundle.py", line 524, in _merge_and_apply
	kwargs=item_data)
  File "~/.local/lib/python3.3/site-packages/webassets/merge.py", line 277, in apply
	return self._wrap_cache(key, func)
  File "~/.local/lib/python3.3/site-packages/webassets/merge.py", line 219, in _wrap_cache
	content = func().getvalue()
  File "~/.local/lib/python3.3/site-packages/webassets/merge.py", line 252, in func
	getattr(filter, type)(data, out, **kwargs_final)
  File "~/.local/lib/python3.3/site-packages/webassets/filter/cssrewrite/base.py", line 78, in input
	self.ctx, source_path, source)
  File "~/.local/lib/python3.3/site-packages/webassets/env.py", line 272, in resolve_source_to_url
	return self.query_url_mapping(ctx, filepath)
  File "~/.local/lib/python3.3/site-packages/webassets/env.py", line 210, in query_url_mapping
	raise ValueError('Cannot determine url for %s' % filepath)
ValueError: Cannot determine url for ../bower_components/fontawesome/css/font-awesome.min.css
```

I added some debug output to the resolve_source_to_url() function:
```
Needle: ../bower_components/fontawesome/css/font-awesome.min.css
Candidate: /var/www/virtual/myuser/apps/five/public/builds
URL: builds/
```
Why is datauri making webassets run the cssrewrite filter?

Thanks in advance!

**Comment by miracle2k** [comment]
The cssrewrite module has a base class for replacing stuff in CSS files that is used by datauri.

This base class tries to determine the url of each source url for use in subclasses. Indeed it appears that that this is unnecessary here, since the datauri filter doesn't really need it.

A fix might be to change CSSUrlRewriter and make ``source_url``, ``output_url`` properties that calculate this on demand.

As for why it cannot find a url for your file, I'm not sure, but you may have misconfigured the environment.

For example, adding directories to ``load_path`` makes webassets not know the url to these files, unless you also add it to ``url_mapping``, or use the ``append_path`` method to begin with.

**Comment by href** [comment]
I have this issue. Without knowing too much about it I assume that my urls cannot be found because I bundle certain files using absolute paths outside the actual source directory.

I worked around the issue by basically implementing this in my own version of the filter:
> A fix might be to change CSSUrlRewriter and make source_url, output_url properties that calculate this on demand.

So the datauri filter does indeed not need to know the url. Since this might be beneficial to others: Is there any demand in implementing this? I wouldn't mind sending a PR to fix this problem in Webassets.
