### ISSUE TITLE
Parse templates error in Jinja2Loader

### ISSUE THREAD

**Issue by manuelbua** [miracle2k/webassets#401]
I'm using flask-assets and it's command line facilities, but the Jinja2Loader fails for some reason, this is the code that fails at `load_bundles`:

```
        loader = Jinja2Loader(env, template_dirs, [app.jinja_env], 
                              jinja_ext=jinja_extension)
        return loader.load_bundles()
```

This is the exception:

```
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    from xyz.console import manager, term
  File "xyz/console/__init__.py", line 16, in <module>
    app, webapp = xyz.run()
  File "xyz/boot.py", line 121, in run
    m.run(['--parse-templates', 'build'])
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/flask_assets.py", line 422, in run
    return impl.main(args)
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/webassets/script.py", line 557, in main
    return self.run_with_argv(argv)
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/webassets/script.py", line 549, in run_with_argv
    return self.run_with_ns(ns)
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/webassets/script.py", line 531, in run_with_ns
    env = self._setup_assets_env(ns, log)
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/flask_assets.py", line 364, in _setup_assets_env
    env.add(*[b for b in self.load_from_templates(env, ns.jinja_extension)
  File "xyz/lib/assets.py", line 26, in load_from_templates
    return Jinja2Loader(env, template_dirs, [jinja2_env], jinja_ext=jinja_extension).\
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/webassets/ext/jinja2.py", line 218, in load_bundles
    bundles.extend(self.with_file(filename, self._parse) or [])
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/webassets/loaders.py", line 301, in with_file
    return then_run(filename, contents)
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/webassets/ext/jinja2.py", line 246, in _parse
    _recurse_node(node)
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/webassets/ext/jinja2.py", line 244, in _recurse_node
    _recurse_node(node)
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/webassets/ext/jinja2.py", line 237, in _recurse_node
    *AssetsExtension.resolve_contents(files.as_const(), self.asset_env),
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/jinja2/nodes.py", line 490, in as_const
    return [x.as_const(eval_ctx) for x in self.items]
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/jinja2/nodes.py", line 561, in as_const
    obj = self.node.as_const(eval_ctx)
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/jinja2/nodes.py", line 604, in as_const
    obj = self.node.as_const(eval_ctx)
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/jinja2/nodes.py", line 365, in as_const
    raise Impossible()
jinja2.nodes.Impossible
```

I'm going to try debug this but i'm not sure why `as_const` gets called on a `Expr` node with `abstract=False`.. anyone seen this already?

**Comment by manuelbua** [comment]
Ok, looks like `assets` arguments in templates MUST be hardcoded strings, for instance, this will fail:

```
{% set bundlename = 'bundle_js_theme_flipzord' %}
{% assets bundlename %}
<script rel="script" type="text/javascript" src="{{ ASSET_URL }}"></script>
{%- endassets %}
```

..but this will work fine:

```
{% assets 'bundle_js_theme_flipzord' %}
<script rel="script" type="text/javascript" src="{{ ASSET_URL }}"></script>
{%- endassets %}
```

**Comment by miracle2k** [comment]
I would say this is the expected behaviour. The loader tries to find the assets tag and reads the name, but it doesn't actually execute the template.

Possible there could be a way around this (executing the template while replacing the tag with a "capture' utility), the question is if it's worth it.
